FROM node:20-alpine

##RUN addgroup -g 1000 app && adduser -u 1000 -G app -s /bin/sh -D app
#RUN groupmod -g 1001 node \
 #  && usermod -u 1001 -g 1001 node
#RUN usermod -o -u 1000 <user>
WORKDIR /app

##USER app

