<?php

return [
    [
        'brand' => 'apple',
        'screenDiagonal' => 8.0,
        'screenResolution' => '3840x2160',
        'os' => 'ios',
        'memory' => 8,
        'cores' => 4,
    ],
    [
        'brand' => 'apple',
        'screenDiagonal' => 7.0,
        'screenResolution' => '2560x1440',
        'os' => 'ios',
        'memory' => 4,
        'cores' => 4,
    ],
    [
        'brand' => 'apple',
        'screenDiagonal' => 6.0,
        'screenResolution' => '1920x1080',
        'os' => 'ios',
        'memory' => 1,
        'cores' => 2,
    ],
    [
        'brand' => 'apple',
        'screenDiagonal' => 7.0,
        'screenResolution' => '3840x2160',
        'os' => 'ios',
        'memory' => 8,
        'cores' => 4,
    ],
    [
        'brand' => 'xiaomi',
        'screenDiagonal' => 5.0,
        'screenResolution' => '1280x1024',
        'os' => 'android',
        'memory' => 4,
        'cores' => 2,
    ],
    [
        'brand' => 'samsung',
        'screenDiagonal' => 6.0,
        'screenResolution' => '1920x1080',
        'os' => 'android',
        'memory' => 8,
        'cores' => 4,
    ],
    [
        'brand' => 'samsung',
        'screenDiagonal' => 5.0,
        'screenResolution' => '1280x1024',
        'os' => 'android',
        'memory' => 4,
        'cores' => 4,
    ],
    [
        'brand' => 'xiaomi',
        'screenDiagonal' => 8.0,
        'screenResolution' => '2560x1440',
        'os' => 'android',
        'memory' => 8,
        'cores' => 8,
    ],
    [
        'brand' => 'samsung',
        'screenDiagonal' => 5.0,
        'screenResolution' => '1920x1080',
        'os' => 'android',
        'memory' => 1,
        'cores' => 8,
    ],
    [
        'brand' => 'xiaomi',
        'screenDiagonal' => 5.0,
        'screenResolution' => '3840x2160',
        'os' => 'android',
        'memory' => 1,
        'cores' => 2,
    ],
    [
        'brand' => 'samsung',
        'screenDiagonal' => 8.0,
        'screenResolution' => '1280x1024',
        'os' => 'android',
        'memory' => 8,
        'cores' => 8,
    ],
    [
        'brand' => 'tecno',
        'screenDiagonal' => 6.0,
        'screenResolution' => '3840x2160',
        'os' => 'android',
        'memory' => 4,
        'cores' => 4,
    ],
    [
        'brand' => 'xiaomi',
        'screenDiagonal' => 7.0,
        'screenResolution' => '1920x1080',
        'os' => 'android',
        'memory' => 4,
        'cores' => 4,
    ],
    [
        'brand' => 'infinix',
        'screenDiagonal' => 6.0,
        'screenResolution' => '1920x1080',
        'os' => 'android',
        'memory' => 8,
        'cores' => 8,
    ],
    [
        'brand' => 'xiaomi',
        'screenDiagonal' => 8.0,
        'screenResolution' => '1920x1080',
        'os' => 'android',
        'memory' => 1,
        'cores' => 2,
    ],
    [
        'brand' => 'samsung',
        'screenDiagonal' => 7.0,
        'screenResolution' => '1920x1080',
        'os' => 'android',
        'memory' => 4,
        'cores' => 8,
    ],
    [
        'brand' => 'honor',
        'screenDiagonal' => 8.0,
        'screenResolution' => '2560x1440',
        'os' => 'android',
        'memory' => 1,
        'cores' => 8,
    ],
    [
        'brand' => 'xiaomi',
        'screenDiagonal' => 8.0,
        'screenResolution' => '3840x2160',
        'os' => 'android',
        'memory' => 4,
        'cores' => 4,
    ],
    [
        'brand' => 'infinix',
        'screenDiagonal' => 7.0,
        'screenResolution' => '1920x1080',
        'os' => 'android',
        'memory' => 8,
        'cores' => 8,
    ],
    [
        'brand' => 'poco',
        'screenDiagonal' => 5.0,
        'screenResolution' => '3840x2160',
        'os' => 'android',
        'memory' => 4,
        'cores' => 2,
    ],
    [
        'brand' => 'huawei',
        'screenDiagonal' => 8.0,
        'screenResolution' => '2560x1440',
        'os' => 'android',
        'memory' => 4,
        'cores' => 2,
    ],
    [
        'brand' => 'realme',
        'screenDiagonal' => 5.0,
        'screenResolution' => '1280x1024',
        'os' => 'android',
        'memory' => 1,
        'cores' => 2,
    ],
];
